server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: admin
    password: password1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  profiles:
    include: oauth

  mustache:
    servlet:
      expose-session-attributes: true